alias g='git'
alias gst='g status'
alias gci='g commit -m'
alias gdiff='g diff'
alias gadd='g add'
alias gdploy='g co deployment && g pull && g merge master && g push && g co master'
alias gdploy_cat='g co deployment && g pull cat deployment && g merge master && g push cat && g co master'
alias gco='g checkout'
alias gcob='gco -b'
alias gpull='g pull'
alias br='branch'
alias gbr='g br'
alias gbrr='g br -r'
alias gpush='g push'
alias gcp='g cherry-pick'

alias sc='ruby script/console'
alias ss='ruby script/server'
alias rg='rails generate'
alias rs='rails server'
alias rc='rails console'
alias cuke='rake cucumber'
alias spec='rake spec'

alias isg='cd ~/git/isg_v5'
alias mc='cd ~/git/mc2010'
alias mynbcs='cd ~/git/hurricane'
alias asky='cd ~/git/australiansky.com'
alias sm='cd ~/git/tbs/simpler_migration'
alias v='cd ~/git/une/vledash'
alias h='heroku'
alias gpo='gpush origin'
alias gph='gpush heroku'
alias gpho='gpush origin ; gpush heroku'

alias logd='tail -f log/development.log'

alias bundlepack='bundle unlock ; bundle install ; bundle lock'

alias mate='open -a TextMate.app'
